[tools]

node = "24"
bun = "latest"
python = "3.11"
elixir = "latest"
uv = "latest"

[plugins]
# python = 'https://github.com/jdxcode/rtx-python'

[settings]
python.uv_venv_auto = true
experimental = true
#idiomatic_version_file_enable_tools = ["python"]
