[tools]
# Runtimes
node = "latest"
bun = "latest"
python = "3.13"
elixir = "latest"

# Python tooling
uv = "latest"

# JS/TS tooling
"npm:typescript" = "latest"
"npm:prettier" = "latest"
"npm:eslint" = "latest"

# CLI tools
"npm:@zvec/zvec-grep" = "latest"
"npm:@tobilu/qmd" = "latest"
"herdr" = "latest"

# Editor / language tooling
lua-language-server = "latest"
tree-sitter = "latest"

[settings]
python.uv_venv_auto = "create|source"
