return {}
-- return {
--
--   -- Lazy
--   {
--     "jackMort/ChatGPT.nvim",
--     event = "VeryLazy",
--     config = function()
--       require("chatgpt").setup({
--         api_key_cmd = "echo ''",
--         api_host_cmd = "echo -n 'http://127.0.0.1:1337'",
--       })
--     end,
--     dependencies = {
--       "MunifTanjim/nui.nvim",
--       "nvim-lua/plenary.nvim",
--       "nvim-telescope/telescope.nvim",
--     },
--   },
-- }
