import = ["~/.config/alacritty/themes/tokyonight_night.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 14.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[window]
blur = true
class = { general = "Alacritty", instance = "Alacritty" }
decorations = "buttonless"
dimensions = { columns = 0, lines = 0 }
dynamic_padding = true
dynamic_title = false
title = "Alacritty"
opacity = 0.5
option_as_alt = "Both"
padding = { x = 4, y = 4 }

[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001F" },
  { key = "Slash", mods = "Control|Shift", chars = "\u001F" },
  { key = "L", mods = "Control", chars = "\u000c" },
  { key = "L", mods = "Control", action = "ClearLogNotice" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "Insert", mods = "Shift", action = "PasteSelection" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Plus", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "F11", mods = "None", action = "ToggleFullscreen" },
  { key = "Paste", mods = "None", action = "Paste" },
  { key = "Copy", mods = "None", action = "Copy" },
  { key = "PageUp", mode = "~Alt", mods = "None", action = "ScrollPageUp" },
  { key = "PageDown", mode = "~Alt", mods = "None", action = "ScrollPageDown" },
  { key = "Home", mode = "~Alt", mods = "Shift", action = "ScrollToTop" },
  { key = "End", mode = "~Alt", mods = "Shift", action = "ScrollToBottom" },
  # { key = "Key0", mods = "Control", chars = "\u001b[48;5u" },
  { key = "Key1", mods = "Control", chars = "\u001b[49;5u" },
  { key = "Key2", mods = "Control", chars = "\u001b[50;5u" },
  { key = "Key3", mods = "Control", chars = "\u001b[51;5u" },
  { key = "Key4", mods = "Control", chars = "\u001b[52;5u" },
  { key = "Key5", mods = "Control", chars = "\u001b[53;5u" },
  { key = "Key6", mods = "Control", chars = "\u001b[54;5u" },
  { key = "Key7", mods = "Control", chars = "\u001b[55;5u" },
  { key = "Key8", mods = "Control", chars = "\u001b[56;5u" },
  { key = "Key9", mods = "Control", chars = "\u001b[57;5u" },
]
