import = ["~/.config/alacritty/themes/tokyonight_night.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 14.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[window]
blur = true
class = { general = "Alacritty", instance = "Alacritty" }
decorations = "buttonless"
dimensions = { columns = 0, lines = 0 }
dynamic_padding = true
dynamic_title = false
title = "Alacritty"
opacity = 0.5
option_as_alt = "Both"
padding = { x = 4, y = 4 }
