-- require('mini.tabline').setup({
--
--   set_vim_settings = false,
--   -- tabpage_section = 'none'
-- })

--
-- local hl = function(thing, opts)
--   vim.api.nvim_set_hl(0, thing, opts)
-- end
--
--
--
-- hl("MiniTablineTabpagesection", {
--   bg = "#333333",
--   fg = "green"
-- })
